Considerable speed improvement!

diff --git a/defaults/.config/polybar/scripts/scratchpad_toggle b/defaults/.config/polybar/scripts/scratchpad_toggle
--- a/defaults/.config/polybar/scripts/scratchpad_toggle
+++ b/defaults/.config/polybar/scripts/scratchpad_toggle
@@ -12,17 +12,17 @@
 
 name="$1"
 Usage="\
-Usage: $(basename $0) <name> <command>
-<name>    : name the window has
-<command> : command used to launch window in case doesnt exist
-E.g.:  $(basename $0) terminal \"exec --no-startup-id i3-sensible-terminal --title=terminal\"
-"
+	Usage: $(basename $0) <name> <command>
+	<name>    : name the window has
+	<command> : command used to launch window in case doesnt exist
+	E.g.:  $(basename $0) terminal \"$TERMINAL --title=terminal\"
+	"
 
 ############## USGCHECKS #################
 
 if [[ $# -lt 1 || "$1" =~ ^(-h|--help)$ || $# -gt 2 ]]; then
-  echo "$Usage"
-  exit 1
+	echo "$Usage"
+	exit 1
 fi
 
 ################ MAIN ####################
@@ -31,20 +31,25 @@ visible_wid="$(xdotool search --onlyvisible --name "^$name$" | tail -1 2> /dev/n
 
 if [[ -z "$visible_wid" ]]; then # If the scratchpad window is not visible
 	wid="$(xdotool search --name "^$name$" | tail -1 2> /dev/null)"
-  if [[ -z "$wid" ]]; then       # If the scratchpad window does not exist
-	  if [[ $# -ne 2 ]]; then    # If a command to launch it was not provided
-		  echo "$name not found. A command was not provided to launch it."
-		  exit 2
-	  fi
+	if [[ -z "$wid" ]]; then       # If the scratchpad window does not exist
+		if [[ $# -ne 2 ]]; then    # If a command to launch it was not provided
+			echo "$name not found. A command was not provided to launch it."
+			exit 2
+		fi
 
-	  echo "$name not found. Using provided command to launch it."
-		i3-msg "$2" || exit $?
-		sleep 1
-  fi
+		echo "$name not found. Using provided command to launch it."
+		eval "$2 &"  || exit $?
+	fi
 
-  echo "$name found. Showing scratchpad."
-  i3-msg "[title="^$name$"] move to scratchpad, scratchpad show"
-  exit $?
+	# Wait for application to be available
+	while [[ -z "$wid" ]]; do
+		sleep 0.005;
+		wid="$(xdotool search --name "^$name$" | tail -1 2> /dev/null)"
+	done
+
+	echo "$name found. Showing scratchpad."
+	i3-msg "[title="^$name$"] move to scratchpad, scratchpad show"
+	exit $?
 fi
 
 echo "Hiding instance of $name."
